### ISSUE TITLE
ERROR ON PAGE RENDER IN BE TYPO3 7.6.32

### ISSUE THREAD

**Issue by mistre85** [pixelant/pxa_siteimprove#23]
Hi, the error is

Too few arguments to function TYPO3\CMS\Core\Authentication\BackendUserAuthentication::getTSConfig(), 0 passed in /Users/paolo.mistretta/Documents/develop/trenord/var/www/typo3/htdocs/typo3conf/ext/pxa_siteimprove/Classes/Hooks/PageRenderer.php on line 55 and at least 1 expected

In typo3 7.6.32

I put a solution to be verified changing this two lines from

&& (!isset($GLOBALS['BE_USER']->getTSConfig()['options.']['siteImprove.']['disable'])
                || !$GLOBALS['BE_USER']->getTSConfig()['options.']['siteImprove.']['disable'])

to

&& !$GLOBALS['BE_USER']->getTSConfigVal('options.siteImprove.disable')

because of definition on getTSConfig

Probably need to put a version check for typo3 version in case is different in other versions.

There are also other 2 problem:

1) the definition of jquery in the script injection that i fixed using $
2) the funciont $tsfe->determineId(); in. var/www/typo3/htdocs/typo3conf/ext/pxa_siteimprove/Classes/Utility/CompatibilityUtility.php, during ajax request stop with exception because $GLOBALS['TT'] is null. i can't make fix on it, because i suppose is a CORE problem.

Thanks

**Comment by mabolek** [comment]
Hi @mistre85!

Thank you for submitting this report. We'll look into it and issue a fix.
