### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by darthnorman** [pixelant/pxa_siteimprove#26]
When trying to login to siteimprove from the page module, the popup gets blocked:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://my2.siteimprove.com/overlay/cms/cmspage?url=https://www.domain.de/&token=[token]. (Reason: CORS request did not succeed).

How would one solve this? Siteimprove would need to set an Access-Control-Allow-Origin header, no?

**Comment by mabolek** [comment]
Hi @darthnorman!

Thank you for making contact.

Which version of the Siteimprove extension and of TYPO3 are you running?

**Comment by darthnorman** [comment]
Hi,
thank you for answering.
I am using the latest version 2.0.2 of pxa_siteimprove on a v8.7.37 TYPO3 installation. Browser is Firefox (Nightly).

**Comment by mabolek** [comment]
Thank you. We'll look into this.

**Comment by mabolek** [comment]
Hi @darthnorman! I'm unable to reproduce this issue Firefox 82.0.2 and TYPO3 8.7.24 with pxa_siteimprove 2.0.2. Are you using standard security settings in Firefox? Do you have this issue in the non-nightly version of Firefox?

**Comment by MattiasNilsson** [comment]
@darthnorman Is this still an issue?

**Comment by darthnorman** [comment]
Hi @MattiasNilsson 
it seems to be no issue anymore, we are using 2.1.0 atm.
Feel free to close the issue, thanks.

**Comment by MattiasNilsson** [comment]
@darthnorman Thanks! 👍

**Comment by honsa** [comment]
@MattiasNilsson the CORS error still appears using the siteimprove overlay in the TYPO3 backend, only if the user is not logged in on siteimprove
