### ISSUE TITLE
[BUG] Token should be fetched automatically and stored in registry

### ISSUE THREAD

**Issue by mabolek** [pixelant/pxa_siteimprove#35]
**Describe the bug**

Fetching the Siteimprove token is currently done by a site administrator by going to `https://my2.siteimprove.com/auth/token`. This is not necessary and does not give information about which integration is using the API.

**Solution**

The `token` parameter should be removed from the `ext_conf_template.txt` file and functionality refactored to automatically fetch the token from `https://my2.siteimprove.com/auth/token?cms=TYPO3`.

The token can be stored in [TYPO3's system registry](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/SystemRegistry/Index.html).

The functionality using the token should be refactored to fetch the token from the registry. 

After updating the extension with this bug fix, the new token can be fetched and persisted to the registry on the first request that requires it. Apart from upgrading the extension, no other action should be necessary.

All documentation pertaining to the token can be removed from the documentation.

**Comment by MattiasNilsson** [comment]
Fixed with: https://github.com/pixelant/pxa_siteimprove/pull/37
