### ISSUE TITLE
[BUG] SiteNotFoundException for editors 

### ISSUE THREAD

**Issue by rtpdho** [pixelant/pxa_siteimprove#47]
Hey, 
if I'm editing a sysfolder which lying outside of a pagetree/globe (multisite setup, some sysfolders globally used) as an editor, I get the following error (because it couldn't find a first page in rootline for these sysfolders ...): 

`#1521716622 TYPO3\CMS\Core\Exception\SiteNotFoundException
No site found in root line of page 12`

`in /var/www/html/web/typo3/sysext/core/Classes/Site/SiteFinder.php line 135
...
at TYPO3\CMS\Core\Site\SiteFinder->getSiteByPageId(12)
in /var/www/html/web/typo3conf/ext/pxa_siteimprove/Classes/Utility/CompatibilityUtility.php line 46
...
at Pixelant\PxaSiteimprove\Utility\CompatibilityUtility::getFirstDomainInRootline(12)
in /var/www/html/web/typo3conf/ext/pxa_siteimprove/Classes/Hooks/PageRenderer.php line 85
`

Thanks in advance, 
David

**Comment by rtpdho** [comment]
Using TYPO3 11.5.5 (PHP8) with pxa_siteimprove 4.0.1

**Comment by MattiasNilsson** [comment]
@rtpdho We have 2 new release for each of our versions, can you verify?

https://github.com/pixelant/pxa_siteimprove/releases/tag/v4.0.2
https://github.com/pixelant/pxa_siteimprove/releases/tag/v3.0.3

**Comment by rtpdho** [comment]
@MattiasNilsson works like a charm, thank you very much!
